export const CARD_SET = [
  'Basic',
  'Classic',
  'Hall of Fame',
  'Missions',
  'Demo',
  'System',
  'Debug',
  'Promo',
  'Naxxramas',
  'Goblins vs Gnomes',
  'Blackrock Mountain',
  'The Grand Tournament',
  'Credits',
  'Hero Skins',
  'Tavern Brawl',
  'The League of Explorers',
  'Whispers of the Old Gods',
  'One Night in Karazhan',
  'Mean Streets of Gadgetzan',
  "Journey to Un'Goro",
  'Knights of the Frozen Throne',
  'Kobolds & Catacombs',
  'The Witchwood',
  'The Boomsday Project',
  "Rastakhan's Rumble",
  'Rise of Shadows',
  'Taverns of Time',
  'Saviors of Uldum',
  'Descent of Dragons',
  "Galakrond's Awakening",
  'Ashes of Outland',
  'Wild Event',
  'Scholomance Academy',
  'Battlegrounds',
  'Demon Hunter Initiate',
  'Madness At The Darkmoon Faire',
  'Forged in the Barrens',
  'Legacy',
  'Core',
  'Vanilla',
  'Wailing Caverns',
  'United in Stormwind',
  'Mercenaries'
];
